stages:
  load_and_save:
    cmd:
      - python src/stage_01_load_save.py --config=config/config.yaml
    deps:
      - src/stage_01_load_save.py
      - src/utils/all_utils.py
      - config/config.yaml
    outs:
      - data

  prepare_base_model:
    cmd:
      - python src/stage_02_prepare_base_model.py --config=config/config.yaml --params=params.yaml
    deps:
      - src/stage_02_prepare_base_model.py
      - src/utils/all_utils.py
      - src/utils/models.py
      - config/config.yaml
      - data
    params:
      - IMAGE_SIZE
      - CLASSES
      - LEARNING_RATE
    outs:
      - artifacts\base_model

  prepare_callbacks:
    cmd:
      - python src/stage_03_prepare_callback.py --config=config/config.yaml --params=params.yaml
    deps:
      - src/stage_03_prepare_callback.py
      - src/utils/all_utils.py
      - src/utils/callbacks.py
      - config/config.yaml
      - params.yaml
    outs:
      - artifacts\callbacks

  train:
    cmd:
      - python src/stage_04_train.py --config=config/config.yaml --params=params.yaml
    deps:
      - src/stage_04_train.py
      - src/utils/all_utils.py
      - src/utils/callbacks.py
      - src/utils/models.py
      - src/utils/data_management.py
      - config/config.yaml
      - artifacts/base_model/updated_VGG16_base_model.h5
      - artifacts/callbacks
    params:
      - IMAGE_SIZE
      - BATCH_SIZE
      - AUGMENTATION
      - EPOCHS
    outs:
      - artifacts/smodel